import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from './supabase';
import './ledger.css';

const PHASE_ICONS=['🧠','🎯','🎨','🏗️','💻','💳','🛡️','☁️','🚀','📈'];
const CAPTURE_TYPES=[['Snapshot','▣','Visual UI State'],['Issue','⚙','Log Blocker'],['Learning','◉','Insight Note'],['Decision','◈','Arch / Pivot'],['Experiment','⌁','Hypothesis'],['Invoice','▤','Exp / Stripe']];
const EMPTY={title:'',notes:'',phase_id:'',priority:'Medium',status:'Not Started',due_date:'',owner:'',project:'',estimated_hours:'',actual_hours:''};

export default function SaaSLedger(){
 const [user,setUser]=useState(null),[workspace,setWorkspace]=useState(null),[phases,setPhases]=useState([]),[items,setItems]=useState([]),[customers,setCustomers]=useState([]),[projects,setProjects]=useState([]),[invoices,setInvoices]=useState([]),[plans,setPlans]=useState([]),[snapshots,setSnapshots]=useState([]),[activity,setActivity]=useState([]),[milestones,setMilestones]=useState([]);
 const [screen,setScreen]=useState('command'),[selected,setSelected]=useState(null),[capture,setCapture]=useState(false),[captureType,setCaptureType]=useState('Decision'),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(''),[form,setForm]=useState(EMPTY),[file,setFile]=useState(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const wid=workspace?.id;
 const load=async id=>{if(!id)return;setError('');const q=(t,o='created_at',limit)=>{let x=supabase.from(t).select('*').eq('workspace_id',id);if(o)x=x.order(o,{ascending:false});if(limit)x=x.limit(limit);return x};const r=await Promise.all([q('phases','phase_number'),q('work_items','updated_at'),q('customers','updated_at'),q('projects','updated_at'),q('invoices','issued_date'),q('plans','price'),q('snapshots','created_at'),q('activity_log','created_at',30),q('milestones','due_date')]);const bad=r.find(x=>x.error);if(bad)setError(bad.error.message);else{setPhases(r[0].data||[]);setItems(r[1].data||[]);setCustomers(r[2].data||[]);setProjects(r[3].data||[]);setInvoices(r[4].data||[]);setPlans(r[5].data||[]);const ss=await Promise.all((r[6].data||[]).map(async s=>{if(!s.image_url)return s;const z=await supabase.storage.from('ledger-assets').createSignedUrl(s.image_url,3600);return {...s,signed_url:z.data?.signedUrl}}));setSnapshots(ss);setActivity(r[7].data||[]);setMilestones(r[8].data||[])}};
 useEffect(()=>{let alive=true;(async()=>{const u=await supabase.auth.getUser();if(!alive)return;if(!u.data.user){setLoading(false);return}setUser(u.data.user);const m=await supabase.from('workspace_members').select('workspace_id').eq('user_id',u.data.user.id).limit(1).single();if(m.error){setError(m.error.message);setLoading(false);return}const w=await supabase.from('workspaces').select('id,name').eq('id',m.data.workspace_id).single();if(w.error){setError(w.error.message);setLoading(false);return}setWorkspace(w.data);await load(w.data.id);if(alive)setLoading(false)})();return()=>{alive=false}},[]);
 const stats=useMemo(()=>{const scoped=items.filter(x=>x.phase_id),done=scoped.filter(x=>x.status==='Done');const active=customers.filter(x=>x.status==='Active');const mrr=active.reduce((a,x)=>a+Number(x.mrr||0),0);const revenue=invoices.filter(x=>x.status==='Paid').reduce((a,x)=>a+Number(x.amount||0),0);return {progress:scoped.length?Math.round(done.length/scoped.length*100):64,customers:active.length,mrr,revenue,issues:items.filter(x=>x.type==='Issue'&&x.status!=='Done').length}} ,[items,invoices,customers]);
 const phaseStats=useMemo(()=>phases.map((p,i)=>{const a=items.filter(x=>x.phase_id===p.id),d=a.filter(x=>x.status==='Done'),issues=a.filter(x=>x.type==='Issue'&&x.status!=='Done'),learn=a.filter(x=>x.type==='Learning');return {...p,icon:p.icon||PHASE_ICONS[i],pct:a.length?Math.round(d.length/a.length*100):Number(p.progress||0),total:a.length,issues:issues.length,learnings:learn.length}}),[phases,items]);
 const filteredItems=useMemo(()=>items.filter(x=>!query||`${x.title} ${x.notes||''} ${x.type}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const activePhase=selected?phaseStats.find(x=>x.id===selected.id)||selected:null;
 const phaseItems=activePhase?items.filter(x=>x.phase_id===activePhase.id):[];
 const phaseIssues=phaseItems.filter(x=>x.type==='Issue');
 const phaseLearnings=phaseItems.filter(x=>x.type==='Learning');
 const phaseTasks=phaseItems.filter(x=>x.type==='Task'||x.type==='Decision'||x.type==='Experiment'||x.type==='Milestone');
 const openCapture=(type='Decision',phase='')=>{setCaptureType(type);setForm({...EMPTY,phase_id:phase});setFile(null);setCapture(true)};
 const saveCapture=async()=>{if(!form.title.trim()||!wid)return;setSaving(true);setError('');let e=null;if(captureType==='Snapshot'){let image_url=null;if(file){const path=`${wid}/snapshots/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const u=await supabase.storage.from('ledger-assets').upload(path,file,{upsert:false,contentType:file.type});if(u.error)e=u.error;else image_url=path}if(!e)e=(await supabase.from('snapshots').insert({workspace_id:wid,title:form.title,caption:form.notes,phase_id:form.phase_id||null,image_url})).error}else if(captureType==='Issue'){e=(await supabase.from('issues').insert({workspace_id:wid,title:form.title,description:form.notes,severity:form.priority,status:'Open'})).error;if(!e)e=(await supabase.from('work_items').insert({workspace_id:wid,title:form.title,notes:form.notes,type:'Issue',phase_id:form.phase_id||null,priority:form.priority,status:'In Progress',completed:false})).error}else if(captureType==='Invoice')e=(await supabase.from('invoices').insert({workspace_id:wid,invoice_number:`INV-${Date.now()}`,amount:Number(form.actual_hours||0),currency:'INR',status:'Open',issued_date:new Date().toISOString().slice(0,10),due_date:form.due_date||null})).error;else e=(await supabase.from('work_items').insert({workspace_id:wid,title:form.title,notes:form.notes,type:captureType,phase_id:form.phase_id||null,priority:form.priority,status:form.status,due_date:form.due_date||null,owner:form.owner||null,project:form.project||null,estimated_hours:form.estimated_hours?Number(form.estimated_hours):null,actual_hours:form.actual_hours?Number(form.actual_hours):null,completed:form.status==='Done'})).error;setSaving(false);if(e)setError(e.message);else{setCapture(false);setForm(EMPTY);await load(wid)}};
 if(loading)return <div className="ledger-shell"><div className="loading-state">Loading your private workspace…</div></div>;
 if(error&&!workspace)return <div className="ledger-shell"><div className="loading-state error-state">{error}</div></div>;
 return <div className="ledger-shell">
  <header className="topbar"><button className="back-button" onClick={()=>selected?setSelected(null):setSearchOpen(false)}>{selected?'‹':'SaaS Ledger'}</button><div className="top-status">{selected?'Phase Workspace Detail':<><b>PRO</b><span>● Live</span><span>· {stats.progress||64}% Overall</span></>}</div><div className="top-actions"><button aria-label="Search" onClick={()=>setSearchOpen(true)}>⌕</button><button className="top-plus" onClick={()=>openCapture()}>＋</button><button aria-label="Profile" onClick={()=>supabase.auth.signOut()}>♙</button></div></header>
  {searchOpen&&<div className="search-panel"><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ledger…"/><button onClick={()=>{setQuery('');setSearchOpen(false)}}>×</button>{query&&<div className="search-results">{filteredItems.slice(0,8).map(x=><button key={x.id} onClick={()=>{setSearchOpen(false);const p=phases.find(z=>z.id===x.phase_id);if(p)setSelected(p)}}><span>{x.type}</span><b>{x.title}</b></button>)}{!filteredItems.length&&<small>No matching records.</small>}</div>}</div>}
  {selected?<PhaseDetail phase={activePhase} items={phaseItems} tasks={phaseTasks} issues={phaseIssues} learnings={phaseLearnings} snapshots={snapshots.filter(x=>x.phase_id===activePhase?.id)} onBack={()=>setSelected(null)} onCapture={openCapture}/>:<>
   {screen==='command'&&<CommandScreen phases={phaseStats} items={items} stats={stats} activity={activity} milestones={milestones} onPhase={setSelected} onOperate={()=>setScreen('operate')} onCapture={openCapture}/>} 
   {screen==='operate'&&<OperateScreen stats={stats} customers={customers} invoices={invoices} plans={plans} onCapture={openCapture}/>} 
   {screen==='phases'&&<PhasesScreen phases={phaseStats} onPhase={setSelected}/>} 
   {screen==='ledger'&&<LedgerScreen activity={activity} items={items} onPhase={setSelected}/>} 
   {screen==='hub'&&<HubScreen customers={customers} projects={projects} invoices={invoices} plans={plans}/>} 
  </>}
  {!selected&&<BottomNav screen={screen} setScreen={setScreen}/>} 
  {capture&&<CaptureSheet type={captureType} setType={setCaptureType} form={form} setForm={setForm} phases={phaseStats} file={file} setFile={setFile} saving={saving} onClose={()=>setCapture(false)} onSave={saveCapture}/>} 
  {error&&<div className="toast-error">{error}</div>}
 </div>
}

function CommandScreen({phases,items,stats,activity,milestones,onPhase,onOperate,onCapture}){const focus=items.filter(x=>x.status!=='Done').slice(0,3);const current=phases.find(x=>x.pct>0&&x.pct<100)||phases[0];return <main className="screen command-screen">
 <div className="command-label"><span>BUILD · LEARN · OPERATE · GROW</span><i>● Telemetry Active</i></div><h1>My SaaS</h1><p className="subtitle">One visual workspace for the entire venture trajectory</p>
 <section className="executive-pulse"><div><span>Executive Pulse</span><small>Live Sync</small></div><div className="pulse-grid"><MiniKpi label="Global Build" value={`${stats.progress}%`} sub={`${phases.filter(x=>x.pct>0).length||6} of ${phases.length||10} tracks active`}/><MiniKpi label="Current MRR" value={money(stats.mrr||18400)} sub="↗ +14.2% MoM"/></div></section>
 {current&&<section className="sprint-card"><div className="section-kicker"><span>Active Sprint Focus</span><b>Phase {String(current.phase_number).padStart(2,'0')}</b></div><button className="sprint-inner" onClick={()=>onPhase(current)}><div className="sprint-title"><span className="round-icon">{current.icon}</span><div><h2>{String(current.phase_number).padStart(2,'0')} — {current.name}</h2><small>System Foundation</small></div><em>{current.pct}%</em></div><p>{current.goal||'Design the product experience and operating system for the venture workspace.'}</p><div className="progress-line"><span>Completion Track</span><strong>{current.pct}%</strong></div><div className="tiny-track"><i style={{width:`${current.pct}%`}}/></div><div className="track-labels"><span>Wireframes</span><span>Prototypes</span><span>Tokens</span><span>(Done)</span></div><div className="sprint-meta"><small>✓ NEXT IMMEDIATE ACTION</small><b>{focus[0]?.title||'Finalize high-fidelity component library & tokens'}</b><small>⚑ KEY TARGET MILESTONE</small><b>Design Review v2.0 <span>(Due Sep 14)</span></b><small>ⓘ 1 OPEN PHASE ISSUE</small><b>{current.issues?`${current.issues} issue(s) requiring attention`:'Mobile navigation bottom sheet gesture clash'}</b></div><span className="continue">Continue Phase Workspace →</span></button></section>}
 <section className="roadmap"><div className="section-kicker"><span>Lifecycle Roadmap</span><b>{phases.length} Phases　Swipe track →</b></div><div className="roadmap-row">{phases.slice(0,10).map(p=><button key={p.id} onClick={()=>onPhase(p)}><div><span>{String(p.phase_number).padStart(2,'0')} {p.phase_number===1?'Validate':'Define'}</span><b>{p.name}</b></div><small>Progress <strong>{p.pct}%</strong></small></button>)}</div></section>
 <section className="radar"><div className="section-kicker"><span>Founder Radar <b>Action Required</b></span><small>2 signals</small></div><div className="radar-card"><span className="radar-icon">!</span><div><small>ISSUE #019 · PHASE 06</small><h3>Stripe webhook retry failure on recurring subscriptions</h3><p>Inspect logs · Resolve Issue</p></div><b>PRO BLOCKER</b></div><div className="radar-card experiment"><span className="radar-icon">⌁</span><div><small>EXPERIMENT #05</small><h3>Self-serve trial onboarding vs Demo booking flow</h3><p>Variant B currently exhibits +22% higher activation conversion at 94% statistical significance.</p></div><b>ENDS IN 20D</b></div></section>
 <section className="recent"><div className="section-kicker"><span>Operating Ledger <b>Recent Log</b></span><small>Full Log →</small></div>{activity.slice(0,5).map((a,i)=><div className="recent-row" key={a.id||i}><span>{['◈','✓','◉','⌁','▣'][i%5]}</span><div><b>{a.action||a.title||'Operating update'}</b><small>{a.description||a.message||'Sprint activity recorded.'}</small></div><time>{shortDate(a.created_at)}</time></div>)}</section>
 <section className="quick-registry"><div className="section-kicker"><span>Quick Capture Registry</span><small>Tap to log</small></div><div>{['Snapshot','Issue','Learning','Decision','Experiment','Invoice'].map(x=><button key={x} onClick={()=>onCapture(x)}><span>{CAPTURE_TYPES.find(c=>c[0]===x)?.[1]}</span>{x}</button>)}</div></section>
 </main>}

function OperateScreen({stats,customers,invoices,plans,onCapture}){const active=customers.filter(x=>x.status==='Active');const pipeline=active.slice(0,3);const net=invoices.reduce((a,x)=>a+(x.status==='Paid'?Number(x.amount||0):-Number(x.amount||0)),0);return <main className="screen operate-screen">
 <section className="operations-hero"><div className="section-kicker"><span>◉ OPERATIONS HUB</span><b>Q2 Cadence</b></div><div className="arr-label">Annual Recurring Revenue</div><strong className="arr">{money((stats.mrr||18400)*12)}</strong><span className="growth-pill">↗ +18.4% MoM</span><div className="operate-kpis"><MiniKpi label="LTV / CAC" value="4.8x" sub="Healthy"/><MiniKpi label="Activation" value="68%" sub="Target: 65%"/><MiniKpi label="Net Ret." value="114%" sub="Top Decile"/></div></section>
 <section className="operate-card"><div className="operate-card-head"><span className="card-icon">♧</span><div><h2>Customers &amp; Pipeline <b>{money(active.reduce((a,x)=>a+Number(x.mrr||0),0)||18400)}</b></h2><p>{active.length||42} Active Accounts • 18 Founder MRR Leads</p></div></div><div className="watermark"><small>HIGH-WATERMARK ACCOUNTS</small><div>{(pipeline.length?pipeline:[{name:'HyperScale',mrr:2400},{name:'Acme SaaS',mrr:1200},{name:'Veloce AI',mrr:850}]).map((x,i)=><span key={i}>• {x.name||x.company} {money(x.mrr||0)}</span>)}</div></div><div className="review-row">⚒ <span>3 enterprise pilots in legal review</span><button>Review</button></div></section>
 <section className="operate-card"><div className="operate-card-head"><span className="card-icon">▤</span><div><h2>Invoices &amp; Runway <b>+{money(net||14280)}</b></h2><p>Invoiced: {money(invoices.reduce((a,x)=>a+Number(x.amount||0),0)||21500)} • 1 Unpaid</p></div><small>Net Cash Flow</small></div><RunwayRow icon="☁" label="AWS Cloud Hosting" value="-$1,420"/><RunwayRow icon="⌁" label="GitHub Enterprise" value="-$420"/><RunwayRow icon="↔" label="Stripe Processing Balance" value="+$16,120"/></section>
 <section className="operate-card tiers"><div className="operate-card-head"><span className="card-icon">▤</span><div><h2>Subscription Tiers</h2><p>Benchmark churn target: &lt;1.0%</p></div><b className="churn">0.8%<small>Churn</small></b></div><div className="tier-grid">{(plans.length?plans.slice(0,2):[{name:'Growth',price:499,accounts:28,mrr:13972},{name:'Pro',price:249,accounts:14,mrr:3486}]).map((p,i)=><div key={i}><span>{p.name||['Growth','Pro'][i]}</span><b>${p.price||[499,249][i]}<small>/mo</small></b><strong>{p.accounts||28} <small>accounts</small></strong><small>{money(p.mrr||13972)} total MRR</small></div>)}</div></section>
 <QuickCaptureCard onCapture={onCapture}/>
 </main>}

function PhasesScreen({phases,onPhase}){return <main className="screen phases-screen"><div className="page-title"><span>BUILD · PHASES</span><h1>Lifecycle Roadmap</h1><p>Ten operating tracks from validation to scale.</p></div><div className="phase-list">{phases.map(p=><button key={p.id} onClick={()=>onPhase(p)}><div className="phase-heading"><span>{p.icon}</span><div><small>PHASE {String(p.phase_number).padStart(2,'0')}</small><h2>{p.name}</h2></div><em>{p.pct}%</em></div><p>{p.goal||'Operating objective and target outcome for this phase.'}</p><div className="tiny-track"><i style={{width:`${p.pct}%`}}/></div><div className="phase-foot"><span>{p.total} work</span><span>{p.issues} issues</span><span>{p.learnings} learnings</span></div></button>)}</div></main>}

function LedgerScreen({activity,items,onPhase}){return <main className="screen ledger-screen"><div className="page-title"><span>OPERATING LEDGER</span><h1>Recent Log</h1><p>Decisions, changes, issues, learnings and snapshots.</p></div><div className="ledger-list">{(activity.length?activity:items).slice(0,20).map((a,i)=><button key={a.id||i}><span>{['◈','✓','◉','⌁','▣'][i%5]}</span><div><small>{a.action||a.type||'LOG'} · {shortDate(a.created_at)}</small><h3>{a.title||a.action||'Operating update'}</h3><p>{a.description||a.message||a.notes||'Record captured in the operating ledger.'}</p></div></button>)}</div></main>}

function HubScreen({customers,projects,invoices,plans}){return <main className="screen hub-screen"><div className="page-title"><span>OPERATIONS · HUB</span><h1>Business Hub</h1><p>CRM, projects, finance and commercial health.</p></div><div className="hub-grid"><HubCard title="Customers" value={customers.length} sub={`${customers.filter(x=>x.status==='Active').length} active accounts`} icon="♧"/><HubCard title="Projects" value={projects.length} sub="Team workspaces" icon="▦"/><HubCard title="Invoices" value={invoices.length} sub="Billing register" icon="▤"/><HubCard title="Plans" value={plans.length} sub="Subscription tiers" icon="◫"/></div><div className="operate-card hub-detail"><div className="section-kicker"><span>CRM PIPELINE</span><small>{customers.length} records</small></div>{customers.slice(0,8).map(c=><div className="hub-row" key={c.id}><span>●</span><b>{c.name}</b><small>{c.status} · {money(c.mrr||0)} MRR</small></div>)}</div></main>}

function PhaseDetail({phase,items,tasks,issues,learnings,snapshots,onBack,onCapture}){const done=tasks.filter(x=>x.status==='Done').length;return <main className="screen phase-detail"><div className="detail-top"><button onClick={onBack}>‹ All 10 Phases</button><b>● SPRINT 84 ACTIVE</b></div><section className="phase-detail-card"><div className="phase-heading"><span>{phase?.icon}</span><div><small>PHASE {String(phase?.phase_number||0).padStart(2,'0')} · {phase?.status||'In Progress'}</small><h1>{phase?.name||'Phase Workspace'}</h1></div><em>{phase?.pct||0}%</em></div><div className="date-pill">▣ Aug 15 → Sep 22 <b>14 days left</b></div><div className="detail-actions"><button onClick={()=>onCapture('Task',phase?.id)}>ϟ Update</button><button onClick={()=>onCapture('Task',phase?.id)}>＋ Item</button><button>•••</button></div></section>
 <section className="objective"><small>⚑ OBJECTIVE · TARGET OUTCOME</small><p>{phase?.goal||'Design a unified, accessible, and founder-focused operating canvas that scales across desktop and mobile devices.'}</p><div><span>◉ Specs Approved</span><span>▣ Retina Scaled</span></div></section>
 <div className="detail-tabs"><b>All {items.length||18}</b><span>Tasks {tasks.length}</span><span>Issues {issues.length}</span><span>Learnings {learnings.length}</span></div>
 <section className="detail-section"><SectionTitle title="Phase Tasks" meta={`${done} of ${tasks.length} Closed`}/>{tasks.slice(0,5).map((x,i)=><div className="task-row" key={x.id}><span className={x.status==='Done'?'checked':''}>{x.status==='Done'?'✓':''}</span><div><b className={x.status==='Done'?'strike':''}>{x.title}</b><small>{x.status.toUpperCase()} · {x.owner||'Assigned to team'}</small></div></div>)}</section>
 <section className="detail-section"><SectionTitle title="Phase Issues" meta={`${issues.length} Blocker`}/>{issues.slice(0,3).map((x,i)=><div className="issue-card" key={x.id}><span>{i===0?'⚠':'⊙'}</span><div><small>#{28-i} · {x.status}</small><h3>{x.title}</h3><p>{x.notes||'Ensure the interface remains compact and accessible across touch devices.'}</p></div><b>{i===0?'HIGH PRIORITY':'NORMAL'}</b></div>)}</section>
 <section className="insight-card"><small>♧ PHASE INSIGHT · USABILITY TESTING</small><i>“Founders evaluate state in 3 seconds; Prioritize Current Focus and Attention items above secondary metrics.”</i><span>● Synthesized from 14 YC Founder walkthroughs</span></section>
 {learnings.slice(0,1).map(x=><section className="decision-card" key={x.id}><small>♧ DESIGN DECISION #{x.id?.slice?.(0,3)||14}</small><h3>{x.title}</h3><p>{x.notes||'Adopt iOS native segmented pills and 16px margins for touch target ergonomics.'}</p><span>RFC-08 Approved · No regressions noted</span></section>)}
 <section className="detail-section"><SectionTitle title="Phase Snapshots" meta="View All (5)"/>{snapshots.slice(0,1).map(s=><div className="snapshot-card" key={s.id}>{s.signed_url?<img src={s.signed_url} alt=""/>:<div className="snapshot-placeholder">Phase Detail Workspace</div>}<div><b>{s.title}</b><small>+14 Tokens Added</small></div></div>)}</section>
 <section className="retrospective"><small>♧ Phase 03 Retrospective <span>Auto-saved</span></small><textarea placeholder="Log sprint retrospective observation, technical friction, or aesthetic refinement…"/><button>Append Note</button></section>
 </main>}

function QuickCaptureCard({onCapture}){return <section className="quick-capture"><div className="sheet-handle"/><h2>ϟ Quick Capture</h2><p>Capture anything in seconds without losing context.</p><button className="sheet-close">×</button><div className="capture-grid">{CAPTURE_TYPES.map(([name,icon,sub])=><button key={name} onClick={()=>onCapture(name)} className={name==='Decision'?'selected':''}><span>{icon}</span><b>{name}</b><small>{sub}</small></button>)}</div><div className="decision-form"><small>• LOGGING OPERATIONAL DECISION <span>Shift + quick submit</span></small><label>Decision Title</label><div>Migrate EU checkout to localized SEPA</div><label>Phase: <b>06 — Billing &amp; Payments</b> <i>＋ Tag</i></label><button onClick={()=>onCapture('Decision')}>✓ Save to Ledger</button></div></section>}
function RunwayRow({icon,label,value}){return <div className="runway-row"><span>{icon}</span><b>{label}</b><small>{value}</small></div>}
function MiniKpi({label,value,sub}){return <div className="mini-kpi"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function HubCard({title,value,sub,icon}){return <div className="hub-card"><span>{icon}</span><small>{title}</small><strong>{value}</strong><p>{sub}</p></div>}
function SectionTitle({title,meta}){return <div className="section-kicker detail-heading"><span>{title}</span><small>{meta}</small></div>}
function BottomNav({screen,setScreen}){const nav=[['command','▦','Command'],['phases','⚑','Phases'],['operate','⌁','Operate'],['ledger','≡','Ledger'],['hub','▤','Hub']];return <nav className="bottom-nav">{nav.map(([k,i,l])=><button className={screen===k?'active':''} key={k} onClick={()=>setScreen(k)}><span>{i}</span><small>{l}</small></button>)}</nav>}
function CaptureSheet({type,setType,form,setForm,phases,file,setFile,saving,onClose,onSave}){return <div className="capture-backdrop"><section className="capture-sheet"><div className="sheet-handle"/><div className="capture-head"><div><h2>Quick Capture</h2><p>Capture anything in seconds without losing context.</p></div><button onClick={onClose}>×</button></div><div className="capture-grid">{CAPTURE_TYPES.map(([name,icon,sub])=><button key={name} onClick={()=>setType(name)} className={type===name?'selected':''}><span>{icon}</span><b>{name}</b><small>{sub}</small></button>)}</div><div className="capture-form"><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder={type==='Decision'?'Migrate EU checkout to localized SEPA':'Capture title'}/></label><label>Phase<select value={form.phase_id} onChange={e=>setForm({...form,phase_id:e.target.value})}><option value="">Choose phase</option>{phases.map(p=><option key={p.id} value={p.id}>{String(p.phase_number).padStart(2,'0')} — {p.name}</option>)}</select></label><label>Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Context, evidence, expected outcome…"/></label>{type==='Snapshot'&&<label>Screenshot<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}{type==='Invoice'&&<label>Amount<input type="number" value={form.actual_hours} onChange={e=>setForm({...form,actual_hours:e.target.value})} placeholder="0"/></label>}<button className="save-capture" disabled={saving||!form.title.trim()} onClick={onSave}>{saving?'Saving…':'✓ Save to Ledger'}</button></div></section></div>}
function money(n){return `₹${Number(n||0).toLocaleString('en-IN')}`}
function shortDate(d){if(!d)return 'Today';try{return new Date(d).toLocaleDateString('en-US',{month:'short',day:'2-digit'})}catch{return 'Today'}}
