import React, {useEffect, useMemo, useState} from 'react';
import {supabase} from './supabase';
import './ledger.css';

const NAV=[['all','All'],['build','🏗️ Build'],['knowledge','🧠 Knowledge'],['business','💼 Business'],['growth','📈 Growth']];
const TYPES=['Task','Issue','Learning','Decision','Experiment','Snapshot','Invoice','Milestone'];
const EMPTY={title:'',notes:'',phase_id:'',priority:'Medium',status:'Not Started',due_date:'',owner:'',project:'',version:'',estimated_hours:'',actual_hours:''};

export default function SaaSLedger(){
 const [phases,setPhases]=useState([]),[items,setItems]=useState([]),[stats,setStats]=useState({}),[summary,setSummary]=useState([]),[customers,setCustomers]=useState([]),[plans,setPlans]=useState([]),[invoices,setInvoices]=useState([]),[metrics,setMetrics]=useState([]),[activity,setActivity]=useState([]),[focus,setFocus]=useState([]);
 const [filter,setFilter]=useState('all'),[view,setView]=useState('overview'),[modal,setModal]=useState(false),[type,setType]=useState('Task'),[form,setForm]=useState(EMPTY),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError(''); const qs=await Promise.all([
  supabase.from('phases').select('*').order('phase_number'),supabase.from('work_items').select('*').order('updated_at',{ascending:false}),supabase.from('dashboard_stats').select('*').single(),supabase.from('phase_summary').select('*').order('phase_number'),supabase.from('customers').select('*').order('created_at',{ascending:false}),supabase.from('plans').select('*').order('price'),supabase.from('invoices').select('*').order('issued_date',{ascending:false}),supabase.from('metrics').select('*').order('name'),supabase.from('activity_log').select('*').order('created_at',{ascending:false}).limit(30),supabase.from('focus_queue').select('*').limit(20)
 ]); const err=qs.find(x=>x.error); if(err){setError(err.error.message)} else {setPhases(qs[0].data||[]);setItems(qs[1].data||[]);setStats(qs[2].data||{});setSummary(qs[3].data||[]);setCustomers(qs[4].data||[]);setPlans(qs[5].data||[]);setInvoices(qs[6].data||[]);setMetrics(qs[7].data||[]);setActivity(qs[8].data||[]);setFocus(qs[9].data||[])} setLoading(false)};
 useEffect(()=>{load()},[]);
 const phaseMap=useMemo(()=>Object.fromEntries(phases.map(p=>[p.id,p])),[phases]);
 const filtered=useMemo(()=>items.filter(i=>{const q=search.toLowerCase(); const text=`${i.title} ${i.notes||''} ${i.type}`.toLowerCase(); const navOk=filter==='all'||(filter==='build'&&i.phase_id)||(filter==='knowledge'&&['Learning','Decision'].includes(i.type))||(filter==='business'&&['Invoice'].includes(i.type))||(filter==='growth'&&['Experiment'].includes(i.type)); return navOk&&(!q||text.includes(q));}),[items,filter,search]);
 const openAdd=(t='Task',phase='')=>{setType(t);setForm({...EMPTY,phase_id:phase});setModal(true)};
 const save=async()=>{if(!form.title.trim())return;setSaving(true);setError('');let e=null;
  if(type==='Snapshot'){e=(await supabase.from('snapshots').insert({title:form.title,caption:form.notes,phase_id:form.phase_id||null})).error}
  else if(type==='Issue'){const r=await supabase.from('issues').insert({title:form.title,description:form.notes,severity:form.priority});e=r.error;if(!e){e=(await supabase.from('work_items').insert({title:form.title,notes:form.notes,type:'Issue',phase_id:form.phase_id||null,priority:form.priority,status:form.status,due_date:form.due_date||null,completed:form.status==='Done'})).error}}
  else if(type==='Invoice'){e=(await supabase.from('invoices').insert({invoice_number:`INV-${Date.now()}`,amount:Number(form.actual_hours||0),status:'Open',due_date:form.due_date||null})).error}
  else if(type==='Milestone'){e=(await supabase.from('milestones').insert({title:form.title,description:form.notes,phase_id:form.phase_id||null,due_date:form.due_date||null})).error}
  else {e=(await supabase.from('work_items').insert({title:form.title,notes:form.notes,type,phase_id:form.phase_id||null,priority:form.priority,status:form.status,due_date:form.due_date||null,owner:form.owner||null,project:form.project||null,version:form.version||null,estimated_hours:form.estimated_hours?Number(form.estimated_hours):null,actual_hours:form.actual_hours?Number(form.actual_hours):null,completed:form.status==='Done'})).error}
  setSaving(false);if(e)setError(e.message);else{setModal(false);setForm(EMPTY);load()}
 };
 const toggle=async i=>{const done=i.status!=='Done';const r=await supabase.from('work_items').update({status:done?'Done':'In Progress',completed:done,completed_at:done?new Date().toISOString():null}).eq('id',i.id);if(r.error)setError(r.error.message);else load()};
 if(loading)return <div className="ledger"><div className="loader">Loading your operating ledger…</div></div>;
 return <div className="ledger"><header><div><div className="brand">SAAS OPERATING LEDGER</div><h1>My SaaS</h1><p>One visual workspace for the entire SaaS journey.</p></div><button className="add" onClick={()=>openAdd()}>＋ Add</button></header>
  {error&&<div className="error">{error}</div>}
  <section className="stats"><Stat label="Build progress" value={`${Math.round((stats.build_progress||0)*100)}%`} sub="from completed phase work"/><Stat label="Open issues" value={stats.open_issues||0} sub={`${stats.overdue||0} overdue`}/><Stat label="Revenue" value={`₹${Number(stats.revenue||0).toLocaleString('en-IN')}`} sub={`MRR ₹${Number(stats.mrr||0).toLocaleString('en-IN')}`}/><Stat label="Learnings" value={stats.learnings||0} sub={`${stats.active_customers||0} active customers`}/></section>
  <div className="toolbar"><nav>{NAV.map(([k,v])=><button className={filter===k?'active':''} key={k} onClick={()=>setFilter(k)}>{v}</button>)}</nav><input className="search" placeholder="Search everything…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  <div className="view-tabs">{[['overview','Overview'],['work','Work'],['customers','Customers'],['finance','Finance'],['metrics','Metrics'],['activity','Activity']].map(([k,v])=><button className={view===k?'active':''} onClick={()=>setView(k)} key={k}>{v}</button>)}</div>
  {view==='overview'&&<Overview phases={phases} summary={summary} focus={focus} items={items} onPhase={setSelected} onAdd={openAdd}/>} 
  {view==='work'&&<Work items={filtered} phaseMap={phaseMap} toggle={toggle} onAdd={openAdd}/>} 
  {view==='customers'&&<Customers customers={customers} onAdd={openAdd}/>} 
  {view==='finance'&&<Finance invoices={invoices} plans={plans} onAdd={openAdd}/>} 
  {view==='metrics'&&<Metrics metrics={metrics}/>} 
  {view==='activity'&&<Activity activity={activity}/>} 
  {selected&&<PhaseDrawer phase={selected} items={items.filter(i=>i.phase_id===selected.id)} onClose={()=>setSelected(null)} onAdd={()=>{setSelected(null);openAdd('Task',selected.id)}}/>}
  {modal&&<Capture type={type} setType={setType} form={form} setForm={setForm} phases={phases} onClose={()=>setModal(false)} onSave={save} saving={saving}/>} 
 </div>
}
function Stat({label,value,sub}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Overview({phases,summary,focus,items,onPhase,onAdd}){return <main><div className="section-head"><div><span>BUILD JOURNEY</span><h2>10 phases</h2></div><button className="ghost" onClick={()=>onAdd('Task')}>＋ Work</button></div><div className="phase-grid">{phases.map(p=><PhaseCard key={p.id} phase={p} summary={summary.find(s=>s.id===p.id)} onClick={()=>onPhase(p)}/>)}</div><div className="dashboard-grid"><section className="panel"><div className="section-head"><div><span>INTELLIGENT NEXT ACTION</span><h2>Focus queue</h2></div></div>{focus.slice(0,7).map(i=><div className="focus" key={i.id}><button className={`check ${i.status==='Done'?'done':''}`} onClick={()=>{}}>{i.status==='Blocked'?'!':'→'}</button><div><b>{i.title}</b><small>{i.phase_name||'Unassigned'} · {i.due_date?`Due ${i.due_date}`:'No due date'} · {i.priority}</small></div></div>)}</section><section className="panel"><div className="section-head"><div><span>OPERATING LOG</span><h2>Recent work</h2></div></div>{items.slice(0,7).map(i=><div className="log-row" key={i.id}><span>{i.type}</span><b>{i.title}</b><small>{new Date(i.updated_at).toLocaleDateString()}</small></div>)}</section></div></main>}
function PhaseCard({phase,summary,onClick}){const done=summary?.done_work||0,total=summary?.total_work||0,pct=summary?.progress||0;return <button className="phase" onClick={onClick}><div className="phase-top"><span className="phase-icon">{phase.icon}</span><span className="phase-no">{String(phase.phase_number).padStart(2,'0')}</span></div><h3>{phase.name}</h3><p>{phase.goal}</p><div className="bar"><i style={{width:`${pct}%`}}/></div><div className="phase-bottom"><span>{done}/{total} done · {summary?.open_issues||0} issues</span><b>{pct}%</b></div><small>{summary?.overdue||0} overdue · {summary?.high_priority||0} high priority</small></button>}
function Work({items,phaseMap,toggle,onAdd}){return <main><div className="section-head"><div><span>WORKSPACE</span><h2>{items.length} items</h2></div><button className="ghost" onClick={()=>onAdd('Task')}>＋ New work</button></div><div className="work-grid">{items.map(i=><article className="work" key={i.id}><button className={`check ${i.status==='Done'?'done':''}`} onClick={()=>toggle(i)}>{i.status==='Done'?'✓':'○'}</button><div className="work-body"><div className="work-meta"><span>{i.type}</span><span>{i.priority}</span>{i.phase_id&&<span>{phaseMap[i.phase_id]?.name}</span>}</div><h3>{i.title}</h3>{i.notes&&<p>{i.notes}</p>}<small>{i.status} · {i.due_date?`Due ${i.due_date}`:'No due date'} · {new Date(i.updated_at).toLocaleDateString()}</small></div></article>)}</div></main>}
function Customers({customers,onAdd}){return <main><div className="section-head"><div><span>BUSINESS</span><h2>Customers & CRM</h2></div><button className="ghost" onClick={()=>onAdd('Task')}>＋ Capture customer note</button></div><div className="table-panel">{customers.length?<table><thead><tr><th>Customer</th><th>Status</th><th>Plan</th><th>MRR</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td><b>{c.name}</b><small>{c.email||c.company||''}</small></td><td>{c.status}</td><td>{c.plan||'—'}</td><td>₹{Number(c.mrr||0).toLocaleString('en-IN')}</td></tr>)}</tbody></table>:<Empty text="No customers yet. Capture your first customer in Supabase or through the customer workflow."/>}</div></main>}
function Finance({invoices,plans,onAdd}){return <main><div className="dashboard-grid"><section className="panel"><div className="section-head"><div><span>REVENUE</span><h2>Invoices</h2></div><button className="ghost" onClick={()=>onAdd('Invoice')}>＋ Invoice</button></div>{invoices.map(i=><div className="log-row" key={i.id}><span>{i.status}</span><b>{i.invoice_number}</b><strong>₹{Number(i.amount||0).toLocaleString('en-IN')}</strong></div>)}{!invoices.length&&<Empty text="No invoices yet."/>}</section><section className="panel"><div className="section-head"><div><span>MONETIZATION</span><h2>Plans</h2></div></div>{plans.map(p=><div className="log-row" key={p.id}><b>{p.name}</b><span>{p.interval}</span><strong>₹{Number(p.price||0).toLocaleString('en-IN')}</strong></div>)}{!plans.length&&<Empty text="No plans yet."/>}</section></div></main>}
function Metrics({metrics}){return <main><div className="section-head"><div><span>GROWTH</span><h2>Metrics & targets</h2></div></div><div className="metric-grid">{metrics.map(m=><div className="metric" key={m.id}><span>{m.name}</span><strong>{m.value}{m.unit?' '+m.unit:''}</strong><small>Target: {m.target??'—'} · Direction: {m.direction||'—'}</small></div>)}{!metrics.length&&<Empty text="No metrics yet."/>}</div></main>}
function Activity({activity}){return <main><div className="section-head"><div><span>AUDIT TRAIL</span><h2>Recent activity</h2></div></div><div className="panel">{activity.map(a=><div className="log-row" key={a.id}><span>{a.action}</span><b>{a.description||a.entity_type}</b><small>{new Date(a.created_at).toLocaleString()}</small></div>)}{!activity.length&&<Empty text="No activity yet."/>}</div></main>}
function Empty({text}){return <div className="empty">{text}</div>}
function PhaseDrawer({phase,items,onClose,onAdd}){return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="phase-num">PHASE {phase.phase_number}</div><h2>{phase.icon} {phase.name}</h2><p className="goal">{phase.goal}</p><div className="drawer-stat">{items.filter(i=>i.status==='Done').length} / {items.length} complete</div><h3>Work in this phase</h3>{items.slice(0,12).map(i=><div className="drawer-item" key={i.id}><span>{i.status==='Done'?'✓':'○'}</span>{i.title}</div>)}<button className="primary" onClick={onAdd}>＋ Add work to phase</button></aside></div>}
function Capture({type,setType,form,setForm,phases,onClose,onSave,saving}){const set=(k,v)=>setForm(f=>({...f,[k]:v}));return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span>QUICK CAPTURE</span><h2>Add to your ledger</h2></div><button className="close" onClick={onClose}>×</button></div><div className="type-row">{TYPES.map(t=><button className={type===t?'selected':''} onClick={()=>setType(t)} key={t}>{t}</button>)}</div><input autoFocus placeholder="Title" value={form.title} onChange={e=>set('title',e.target.value)}/><textarea placeholder="Details / notes" value={form.notes} onChange={e=>set('notes',e.target.value)}/><div className="two"><select value={form.phase_id} onChange={e=>set('phase_id',e.target.value)}><option value="">No phase</option>{phases.map(p=><option key={p.id} value={p.id}>Phase {p.phase_number} · {p.name}</option>)}</select><select value={form.priority} onChange={e=>set('priority',e.target.value)}>{['Low','Medium','High','Critical'].map(x=><option key={x}>{x}</option>)}</select></div>{type!=='Snapshot'&&type!=='Invoice'&&type!=='Milestone'&&<div className="two"><select value={form.status} onChange={e=>set('status',e.target.value)}>{['Not Started','In Progress','Done','Blocked'].map(x=><option key={x}>{x}</option>)}</select><input placeholder="Owner" value={form.owner} onChange={e=>set('owner',e.target.value)}/></div>}<div className="two"><input placeholder="Project" value={form.project} onChange={e=>set('project',e.target.value)}/><input placeholder={type==='Invoice'?'Amount (₹)':'Estimated hours'} type="number" value={type==='Invoice'?form.actual_hours:form.estimated_hours} onChange={e=>set(type==='Invoice'?'actual_hours':'estimated_hours',e.target.value)}/></div><div className="two"><input type="date" value={form.due_date} onChange={e=>set('due_date',e.target.value)}/><input placeholder="Version" value={form.version} onChange={e=>set('version',e.target.value)}/></div><div className="modal-actions"><button className="ghost" onClick={onClose}>Cancel</button><button className="primary" disabled={saving} onClick={onSave}>{saving?'Saving…':'Save'}</button></div></div></div>}
