import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from './supabase';
import './executive.css';

const PHASE_ICONS=['🧠','🎯','🎨','🏗️','💻','💳','🛡️','☁️','🚀','📈'];
const ARTIFACT_KINDS=['Document','Code','CI/CD','Docker','Config','Design','Wireframe','Image','Screenshot','API','SQL','Log','Other'];
const NOTE_CATS=['Note','Decision','Learning','Meeting','Requirement','Runbook','Incident'];
const TEST_AREAS=['Functional','Regression','Security','Performance','Accessibility','Billing','Integration','Smoke'];
const TEST_STATUSES=['Not Run','Passed','Failed','Blocked','Skipped'];
const TEST_SEVERITIES=['Low','Medium','High','Critical'];

function emptyArtifact(){return {title:'',kind:'Code',description:'',content:'',external_url:'',phase_id:'',file:null}}
function emptyTest(){return {title:'',area:'Functional',steps:'',expected_result:'',actual_result:'',status:'Not Run',severity:'Medium',environment:'Production',phase_id:''}}
function emptyNote(){return {title:'',body:'',category:'Note',phase_id:'',pinned:false}}

export default function ExecutiveLedger(){
 const [user,setUser]=useState(null),[workspace,setWorkspace]=useState(null),[phases,setPhases]=useState([]),[items,setItems]=useState([]),[checklist,setChecklist]=useState([]),[tests,setTests]=useState([]),[notes,setNotes]=useState([]),[artifacts,setArtifacts]=useState([]),[customers,setCustomers]=useState([]),[invoices,setInvoices]=useState([]),[activity,setActivity]=useState([]);
 const [phaseId,setPhaseId]=useState('all'),[section,setSection]=useState('command'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [artifact,setArtifact]=useState(emptyArtifact()),[test,setTest]=useState(emptyTest()),[note,setNote]=useState(emptyNote());
 const load=async(wid)=>{setBusy(true);setError('');const q=(table,order='created_at')=>supabase.from(table).select('*').eq('workspace_id',wid).order(order,{ascending:false});const r=await Promise.all([q('phases','phase_number'),q('work_items','updated_at'),q('phase_checklist_items','sort_order'),q('test_cases','updated_at'),q('ledger_notes','updated_at'),q('ledger_artifacts','updated_at'),q('customers','updated_at'),q('invoices','issued_date'),q('activity_log','created_at')]);const bad=r.find(x=>x.error);if(bad)setError(bad.error.message);else{setPhases(r[0].data||[]);setItems(r[1].data||[]);setChecklist(r[2].data||[]);setTests(r[3].data||[]);setNotes(r[4].data||[]);setArtifacts(r[5].data||[]);setCustomers(r[6].data||[]);setInvoices(r[7].data||[]);setActivity(r[8].data||[])}setBusy(false)};
 useEffect(()=>{let alive=true;(async()=>{const u=await supabase.auth.getUser();if(!alive)return;if(!u.data.user){setError('No authenticated session');return}setUser(u.data.user);const m=await supabase.from('workspace_members').select('workspace_id').eq('user_id',u.data.user.id).limit(1).single();if(m.error){setError(m.error.message);return}const w=await supabase.from('workspaces').select('id,name').eq('id',m.data.workspace_id).single();if(w.error)setError(w.error.message);else{setWorkspace(w.data);load(w.data.id)}})();return()=>{alive=false}},[]);
 const activePhase=phaseId==='all'?null:phases.find(p=>p.id===phaseId);
 const visibleCheck=useMemo(()=>checklist.filter(x=>phaseId==='all'||x.phase_id===phaseId),[checklist,phaseId]);
 const visibleTests=useMemo(()=>tests.filter(x=>(phaseId==='all'||x.phase_id===phaseId)&&(!query||`${x.title} ${x.steps} ${x.expected_result}`.toLowerCase().includes(query.toLowerCase()))),[tests,phaseId,query]);
 const visibleNotes=useMemo(()=>notes.filter(x=>(phaseId==='all'||x.phase_id===phaseId)&&(!query||`${x.title} ${x.body} ${x.category}`.toLowerCase().includes(query.toLowerCase()))),[notes,phaseId,query]);
 const visibleArtifacts=useMemo(()=>artifacts.filter(x=>(phaseId==='all'||x.phase_id===phaseId)&&(!query||`${x.title} ${x.kind} ${x.description} ${x.content}`.toLowerCase().includes(query.toLowerCase()))),[artifacts,phaseId,query]);
 const stats=useMemo(()=>{const total=items.length,done=items.filter(x=>x.status==='Done').length,failed=tests.filter(x=>x.status==='Failed').length,passed=tests.filter(x=>x.status==='Passed').length,open=items.filter(x=>x.type==='Issue'&&x.status!=='Done').length,revenue=invoices.filter(x=>x.status==='Paid').reduce((a,x)=>a+Number(x.amount||0),0);return {progress:total?Math.round(done/total*100):0,open,failed,passed,revenue,customers:customers.length}},[items,tests,invoices,customers]);
 const phaseStats=useMemo(()=>phases.map(p=>{const a=items.filter(x=>x.phase_id===p.id),d=a.filter(x=>x.status==='Done').length,c=checklist.filter(x=>x.phase_id===p.id),cd=c.filter(x=>x.status==='Done').length,t=tests.filter(x=>x.phase_id===p.id),tf=t.filter(x=>x.status==='Failed').length;return {...p,workPct:a.length?Math.round(d/a.length*100):0,checkPct:c.length?Math.round(cd/c.length*100):0,tests:t.length,failed:tf}}),[phases,items,checklist,tests]);
 const saveChecklist=async(c)=>{const status=c.status==='Done'?'Not Started':'Done';const r=await supabase.from('phase_checklist_items').update({status,updated_at:new Date().toISOString()}).eq('id',c.id).eq('workspace_id',workspace.id);if(r.error)setError(r.error.message);else load(workspace.id)};
 const saveTest=async()=>{if(!test.title.trim())return;setBusy(true);const r=await supabase.from('test_cases').insert({...test,workspace_id:workspace.id,phase_id:test.phase_id||null,run_by:test.status==='Not Run'?null:user.id,run_at:test.status==='Not Run'?null:new Date().toISOString()});setBusy(false);if(r.error)setError(r.error.message);else{setNotice('Test case added');setTest(emptyTest());load(workspace.id)}};
 const saveNote=async()=>{if(!note.title.trim())return;setBusy(true);const r=await supabase.from('ledger_notes').insert({...note,workspace_id:workspace.id,phase_id:note.phase_id||null,created_by:user.id});setBusy(false);if(r.error)setError(r.error.message);else{setNotice('Note saved');setNote(emptyNote());load(workspace.id)}};
 const saveArtifact=async()=>{if(!artifact.title.trim())return;setBusy(true);let path=null;if(artifact.file){path=`${workspace.id}/artifacts/${crypto.randomUUID()}-${artifact.file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const u=await supabase.storage.from('ledger-assets').upload(path,artifact.file,{upsert:false,contentType:artifact.file.type});if(u.error){setError(u.error.message);setBusy(false);return}}const r=await supabase.from('ledger_artifacts').insert({workspace_id:workspace.id,phase_id:artifact.phase_id||null,title:artifact.title,kind:artifact.kind,description:artifact.description,content:artifact.content,external_url:artifact.external_url||null,file_name:artifact.file?.name||null,storage_path:path,mime_type:artifact.file?.type||null,size_bytes:artifact.file?.size||null,created_by:user.id});setBusy(false);if(r.error)setError(r.error.message);else{setNotice('Artifact saved');setArtifact(emptyArtifact());load(workspace.id)}};
 if(!workspace&&!error)return <div className="exec-shell"><div className="exec-loader">Loading operating system…</div></div>;
 return <div className="exec-shell"><header className="exec-header"><div><div className="eyebrow">SAAS OPERATING LEDGER · EXECUTIVE CONSOLE</div><h1>{workspace?.name||'Workspace'}</h1><p>One source of truth for product, engineering, testing, knowledge, releases and growth.</p></div><div className="exec-actions"><button onClick={()=>supabase.auth.signOut()}>Sign out</button><button className="solid" onClick={()=>setSection('capture')}>＋ Capture</button></div></header>{error&&<div className="exec-error">{error}</div>}{notice&&<div className="exec-notice" onClick={()=>setNotice('')}>{notice}</div>}
 <section className="kpi-row"><Kpi label="Build health" value={`${stats.progress}%`} sub="work completed"/><Kpi label="Open issues" value={stats.open} sub="needs attention"/><Kpi label="Test health" value={stats.failed?`${stats.failed} failed`:`${stats.passed} passed`} sub={`${tests.length} total cases`}/><Kpi label="Revenue" value={`₹${stats.revenue.toLocaleString('en-IN')}`} sub={`${stats.customers} customers`}/></section>
 <div className="exec-layout"><aside className="phase-rail"><div className="rail-title">PHASES</div><button className={phaseId==='all'?'phase-nav active':'phase-nav'} onClick={()=>setPhaseId('all')}><b>◎</b><span>Command center</span></button>{phases.map((p,i)=><button key={p.id} className={phaseId===p.id?'phase-nav active':'phase-nav'} onClick={()=>setPhaseId(p.id)}><b>{p.icon||PHASE_ICONS[i]}</b><span><strong>{String(p.phase_number).padStart(2,'0')} · {p.name}</strong><small>{phaseStats.find(x=>x.id===p.id)?.workPct||0}% work · {phaseStats.find(x=>x.id===p.id)?.checkPct||0}% checklist</small></span></button>)}</aside>
 <main className="exec-main"><div className="exec-toolbar"><div className="section-switch">{[['command','Command'],['testing','Testing'],['knowledge','Knowledge'],['artifacts','Artifacts'],['analytics','Analytics'],['capture','Capture']].map(([k,v])=><button className={section===k?'active':''} onClick={()=>setSection(k)} key={k}>{v}</button>)}</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search everything…"/></div>
 {section==='command'&&<Command phases={phases} phaseStats={phaseStats} checklist={visibleCheck} items={items} tests={tests} activePhase={activePhase} onCheck={saveChecklist} onSection={setSection}/>} 
 {section==='testing'&&<Testing tests={visibleTests} phases={phases} value={test} setValue={setTest} save={saveTest} busy={busy}/>} 
 {section==='knowledge'&&<Knowledge notes={visibleNotes} phases={phases} value={note} setValue={setNote} save={saveNote} busy={busy}/>} 
 {section==='artifacts'&&<Artifacts artifacts={visibleArtifacts} phases={phases} value={artifact} setValue={setArtifact} save={saveArtifact} busy={busy}/>} 
 {section==='analytics'&&<Analytics phaseStats={phaseStats} items={items} tests={tests} activity={activity}/>} 
 {section==='capture'&&<CaptureHub setSection={setSection} setPhaseId={setPhaseId}/>} 
 </main></div></div>
}
function Kpi({label,value,sub}){return <div className="kpi"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Command({phases,phaseStats,checklist,items,tests,activePhase,onCheck,onSection}){const ps=activePhase?phaseStats.filter(x=>x.id===activePhase.id):phaseStats;const focus=items.filter(x=>x.status!=='Done').sort((a,b)=>String(a.due_date||'9999').localeCompare(String(b.due_date||'9999'))).slice(0,8);return <>{activePhase&&<div className="hero-phase"><span>{activePhase.icon}</span><div><div className="eyebrow">PHASE {String(activePhase.phase_number).padStart(2,'0')}</div><h2>{activePhase.name}</h2><p>{activePhase.goal}</p></div><button className="solid" onClick={()=>onSection('testing')}>Open testing</button></div>}<section className="panel"><div className="panel-head"><div><span>PHASE SCORECARD</span><h2>{activePhase?'Execution readiness':'All phases at a glance'}</h2></div></div><div className="phase-score-grid">{ps.map(p=><div className="score-card" key={p.id}><div className="score-top"><b>{p.icon} {p.name}</b><strong>{p.workPct}%</strong></div><div className="track"><i style={{width:`${p.workPct}%`}}/></div><div className="score-meta"><span>{p.total_work??items.filter(x=>x.phase_id===p.id).length} work</span><span>{p.checkPct}% checklist</span><span>{p.failed?`${p.failed} failed`:p.tests?`${p.tests} tests`:'No tests'}</span></div></div>)}</div></section><div className="two-panels"><section className="panel"><div className="panel-head"><div><span>DEFINITION OF DONE</span><h2>{checklist.length} checks</h2></div></div>{checklist.slice(0,12).map(c=><button className="check-row" key={c.id} onClick={()=>onCheck(c)}><span className={c.status==='Done'?'check-dot done':'check-dot'}>{c.status==='Done'?'✓':''}</span><span><b>{c.title}</b><small>{c.category} · {c.required?'Required':'Recommended'}</small></span></button>)}{!checklist.length&&<Empty text="Choose a phase to see its operating checklist."/>}</section><section className="panel"><div className="panel-head"><div><span>NEXT ACTIONS</span><h2>Focus queue</h2></div></div>{focus.map(x=><div className="focus-row" key={x.id}><span className={x.priority==='Critical'?'danger':''}>→</span><div><b>{x.title}</b><small>{x.type} · {x.priority} · {x.due_date||'No due date'}</small></div></div>)}{!focus.length&&<Empty text="Nothing open. Great."/>}</section></div></>}
function Testing({tests,phases,value,setValue,save,busy}){return <><section className="panel form-panel"><div className="panel-head"><div><span>TEST CASE BUILDER</span><h2>Turn every bug into a reproducible test</h2></div></div><div className="form-grid"><input placeholder="Test title" value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/><select value={value.phase_id} onChange={e=>setValue({...value,phase_id:e.target.value})}><option value="">No phase</option>{phases.map(p=><option key={p.id} value={p.id}>Phase {p.phase_number} · {p.name}</option>)}</select><select value={value.area} onChange={e=>setValue({...value,area:e.target.value})}>{TEST_AREAS.map(x=><option key={x}>{x}</option>)}</select><select value={value.severity} onChange={e=>setValue({...value,severity:e.target.value})}>{TEST_SEVERITIES.map(x=><option key={x}>{x}</option>)}</select><select value={value.status} onChange={e=>setValue({...value,status:e.target.value})}>{TEST_STATUSES.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Environment / browser / device" value={value.environment} onChange={e=>setValue({...value,environment:e.target.value})}/><textarea placeholder="Reproduction steps (one per line)" value={value.steps} onChange={e=>setValue({...value,steps:e.target.value})}/><textarea placeholder="Expected result" value={value.expected_result} onChange={e=>setValue({...value,expected_result:e.target.value})}/><textarea placeholder="Actual result / evidence" value={value.actual_result} onChange={e=>setValue({...value,actual_result:e.target.value})}/></div><button className="solid" disabled={busy} onClick={save}>＋ Save test case</button></section><section className="panel"><div className="panel-head"><div><span>TEST REGISTER</span><h2>{tests.length} cases</h2></div></div>{tests.map(t=><article className="test-card" key={t.id}><div><span className={`status status-${t.status.toLowerCase().replace(/ /g,'-')}`}>{t.status}</span><span className="muted">{t.severity} · {t.area}</span></div><h3>{t.title}</h3><p>{t.expected_result||'No expected result recorded.'}</p><small>{t.environment} · {t.run_at?new Date(t.run_at).toLocaleString():'Not run yet'}</small></article>)}{!tests.length&&<Empty text="Create your first regression, security, billing or smoke test above."/>}</section></>}
function Knowledge({notes,phases,value,setValue,save,busy}){return <><section className="panel form-panel"><div className="panel-head"><div><span>KNOWLEDGE VAULT</span><h2>Notes, decisions, requirements & runbooks</h2></div></div><div className="form-grid"><input placeholder="Title" value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/><select value={value.category} onChange={e=>setValue({...value,category:e.target.value})}>{NOTE_CATS.map(x=><option key={x}>{x}</option>)}</select><select value={value.phase_id} onChange={e=>setValue({...value,phase_id:e.target.value})}><option value="">No phase</option>{phases.map(p=><option key={p.id} value={p.id}>Phase {p.phase_number} · {p.name}</option>)}</select><label className="toggle"><input type="checkbox" checked={value.pinned} onChange={e=>setValue({...value,pinned:e.target.checked})}/> Pin important note</label><textarea className="wide" placeholder="Write the context, decision, lesson, command, incident, requirement or meeting notes…" value={value.body} onChange={e=>setValue({...value,body:e.target.value})}/></div><button className="solid" disabled={busy} onClick={save}>Save knowledge</button></section><section className="panel"><div className="panel-head"><div><span>KNOWLEDGE TIMELINE</span><h2>{notes.length} entries</h2></div></div>{notes.map(n=><article className={n.pinned?'knowledge-card pinned':'knowledge-card'} key={n.id}><div><span className="status">{n.category}</span>{n.pinned&&<span className="pin">PINNED</span>}</div><h3>{n.title}</h3><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString()}</small></article>)}{!notes.length&&<Empty text="Nothing captured yet."/>}</section></>}
function Artifacts({artifacts,phases,value,setValue,save,busy}){return <><section className="panel form-panel"><div className="panel-head"><div><span>ENGINEERING & DESIGN VAULT</span><h2>Store code, CI/CD, Docker, screenshots and files</h2></div></div><div className="form-grid"><input placeholder="Artifact title" value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/><select value={value.kind} onChange={e=>setValue({...value,kind:e.target.value})}>{ARTIFACT_KINDS.map(x=><option key={x}>{x}</option>)}</select><select value={value.phase_id} onChange={e=>setValue({...value,phase_id:e.target.value})}><option value="">No phase</option>{phases.map(p=><option key={p.id} value={p.id}>Phase {p.phase_number} · {p.name}</option>)}</select><input placeholder="External URL / repository / Figma / issue" value={value.external_url} onChange={e=>setValue({...value,external_url:e.target.value})}/><input type="file" onChange={e=>setValue({...value,file:e.target.files?.[0]||null})}/><textarea className="wide" placeholder="Paste script, YAML, Dockerfile, SQL, API payload, config, code snippet or documentation…" value={value.content} onChange={e=>setValue({...value,content:e.target.value})}/><textarea className="wide" placeholder="Description / why this artifact matters" value={value.description} onChange={e=>setValue({...value,description:e.target.value})}/></div><button className="solid" disabled={busy} onClick={save}>＋ Save artifact</button></section><section className="panel"><div className="panel-head"><div><span>ARTIFACT INDEX</span><h2>{artifacts.length} assets</h2></div></div><div className="artifact-grid">{artifacts.map(a=><article className="artifact-card" key={a.id}><div className="artifact-kind">{a.kind}</div><h3>{a.title}</h3><p>{a.description||'No description.'}</p>{a.content&&<pre>{a.content.slice(0,700)}</pre>}{a.external_url&&<a href={a.external_url} target="_blank" rel="noreferrer">Open external resource ↗</a>}{a.file_name&&<small>📎 {a.file_name}</small>}</article>)}</div>{!artifacts.length&&<Empty text="Add Dockerfiles, GitHub Actions YAML, SQL, design images, wireframes, screenshots, API examples and runbooks here."/>}</section></>}
function Analytics({phaseStats,items,tests,activity}){const max=Math.max(...phaseStats.map(x=>x.workPct),1);const types=['Task','Issue','Learning','Decision','Experiment','Milestone'];const counts=types.map(t=>({name:t,value:items.filter(x=>x.type===t).length}));return <><section className="panel"><div className="panel-head"><div><span>EXECUTIVE VISUALIZATION</span><h2>Build progress by phase</h2></div></div><div className="bar-chart">{phaseStats.map(p=><div className="chart-row" key={p.id}><label>{String(p.phase_number).padStart(2,'0')} {p.name}</label><div className="chart-track"><i style={{width:`${(p.workPct/max)*100}%`}}/></div><b>{p.workPct}%</b></div>)}</div></section><div className="two-panels"><section className="panel"><div className="panel-head"><div><span>WORK MIX</span><h2>Operating load</h2></div></div><div className="donut-wrap"><div className="donut"><div><b>{items.length}</b><small>items</small></div></div><div className="legend">{counts.map(x=><div key={x.name}><i/> <span>{x.name}</span><b>{x.value}</b></div>)}</div></div></section><section className="panel"><div className="panel-head"><div><span>QUALITY SIGNAL</span><h2>Test distribution</h2></div></div><div className="quality-grid">{['Passed','Failed','Blocked','Not Run'].map(s=><div key={s}><strong>{tests.filter(x=>x.status===s).length}</strong><span>{s}</span></div>)}</div><div className="mini-log">{activity.slice(0,8).map(a=><div key={a.id}><span>{a.action}</span><b>{a.description||a.entity_type}</b></div>)}</div></section></div></>}
function CaptureHub({setSection,setPhaseId}){const actions=[['testing','🐛','Issue / test','Reproduce a bug, define expected behavior and attach evidence.'],['knowledge','🧠','Learning','Capture what the team discovered and make it searchable.'],['knowledge','⚖️','Decision','Record context, alternatives, decision and owner.'],['artifacts','⌘','Code / CI/CD','Store snippets, GitHub Actions, Dockerfiles, SQL and configs.'],['artifacts','🎨','Design','Store wireframes, screenshots, exports and design references.'],['knowledge','📋','Requirement','Turn a requirement into a traceable phase artifact.']];return <section className="capture-grid">{actions.map(([s,i,t,d])=><button key={t} onClick={()=>setSection(s)}><span>{i}</span><div><b>{t}</b><small>{d}</small></div><strong>→</strong></button>)}</section>}
function Empty({text}){return <div className="empty">{text}</div>}
