import React,{useMemo,useState} from 'react';
import {FiBell,FiChevronDown,FiChevronLeft,FiChevronRight,FiClock,FiCloud,FiCreditCard,FiDownload,FiGrid,FiHardDrive,FiHelpCircle,FiImage,FiMenu,FiMoreHorizontal,FiPlus,FiSearch,FiSettings,FiShield,FiTrendingUp,FiUsers,FiX,FiCheck,FiUploadCloud} from 'react-icons/fi';
import './momentia.css';

const PHOTOS=[
 {id:1,src:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',title:'Ceremony',tag:'Wedding',ratio:'landscape'},
 {id:2,src:'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=85',title:'First dance',tag:'Reception',ratio:'portrait'},
 {id:3,src:'https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=1200&q=85',title:'Golden hour',tag:'Portraits',ratio:'wide'},
 {id:4,src:'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=900&q=85',title:'Details',tag:'Details',ratio:'portrait'},
 {id:5,src:'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=85',title:'Celebration',tag:'Reception',ratio:'landscape'},
 {id:6,src:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=900&q=85',title:'The couple',tag:'Portraits',ratio:'portrait'},
 {id:7,src:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=85',title:'Reception',tag:'Reception',ratio:'landscape'},
 {id:8,src:'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1200&q=85',title:'Quiet moment',tag:'Candid',ratio:'wide'}
];

const EVENTS=[
 {id:1,name:'Ananya & Rahul',date:'12 Sep 2026',venue:'The Leela Palace, Chennai',status:'Live',photos:1842,published:1720,pending:122,visitors:486,scans:219,cover:PHOTOS[0].src},
 {id:2,name:'Meera & Arjun',date:'18 Sep 2026',venue:'Taj Falaknuma Palace, Hyderabad',status:'Processing',photos:963,published:0,pending:963,visitors:0,scans:0,cover:PHOTOS[4].src},
 {id:3,name:'Kavya & Aditya',date:'28 Sep 2026',venue:'ITC Grand Chola, Chennai',status:'Scheduled',photos:0,published:0,pending:0,visitors:0,scans:0,cover:PHOTOS[2].src},
 {id:4,name:'Nisha & Varun',date:'03 Oct 2026',venue:'Ramoji Film City, Hyderabad',status:'Draft',photos:0,published:0,pending:0,visitors:0,scans:0,cover:PHOTOS[6].src}
];

const NAV=[['dashboard','Dashboard',FiGrid],['events','Events',FiClock],['photos','Photos',FiImage],['team','Team',FiUsers],['analytics','Analytics',FiTrendingUp],['storage','Storage',FiHardDrive],['billing','Billing',FiCreditCard],['support','Support',FiHelpCircle],['settings','Settings',FiSettings]];

export default function MomentiaApp(){
 const [page,setPage]=useState('dashboard');
 const [mobileNav,setMobileNav]=useState(false);
 const [search,setSearch]=useState('');
 const [showCreate,setShowCreate]=useState(false);
 const [event,setEvent]=useState(null);
 const [gallery,setGallery]=useState(false);
 const [favorites,setFavorites]=useState(new Set());
 const [wizard,setWizard]=useState(1);
 const [toast,setToast]=useState('');
 const [createdEvents,setCreatedEvents]=useState([]);
 const allEvents=[...createdEvents,...EVENTS];
 const filteredEvents=useMemo(()=>allEvents.filter(e=>`${e.name} ${e.venue} ${e.status}`.toLowerCase().includes(search.toLowerCase())),[allEvents,search]);
 const notify=(msg)=>{setToast(msg);window.setTimeout(()=>setToast(''),2400)};
 const toggleFav=id=>setFavorites(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
 const createEvent=()=>{setCreatedEvents(e=>[{id:Date.now(),name:'New Wedding Event',date:'To be scheduled',venue:'Venue not set',status:'Draft',photos:0,published:0,pending:0,visitors:0,scans:0,cover:PHOTOS[1].src},...e]);setShowCreate(false);setWizard(1);notify('Event created as a draft');setPage('events')};
 return <div className="momentia-app">
   <Sidebar page={page} setPage={p=>{setPage(p);setMobileNav(false)}} open={mobileNav}/>
   {mobileNav&&<button className="mobile-scrim" onClick={()=>setMobileNav(false)} aria-label="Close navigation"/>}
   <div className="app-shell">
    <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileNav(true)}><FiMenu/></button><div className="crumb">Momentia <span>/</span> {NAV.find(x=>x[0]===page)?.[1]||'Dashboard'}</div><div className="top-actions"><div className="global-search"><FiSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search events, clients, photos…"/></div><button className="icon-btn"><FiBell/><i/></button><button className="profile"><span className="avatar">MS</span><span className="profile-name">Momentia Studio</span><FiChevronDown/></button></div></header>
    <main className="page-content">
      {page==='dashboard'&&<Dashboard events={allEvents} onCreate={()=>setShowCreate(true)} onEvent={setEvent} onPage={setPage} notify={notify}/>} 
      {page==='events'&&<Events events={filteredEvents} onCreate={()=>setShowCreate(true)} onEvent={setEvent}/>} 
      {page==='photos'&&<PhotoLibrary favorites={favorites} toggleFav={toggleFav} onGallery={()=>setGallery(true)}/>} 
      {page==='team'&&<Team/>}
      {page==='analytics'&&<Analytics events={allEvents}/>} 
      {page==='storage'&&<Storage/>}
      {page==='billing'&&<Billing/>}
      {page==='support'&&<Support/>}
      {page==='settings'&&<Settings/>}
    </main>
   </div>
   {showCreate&&<CreateEvent wizard={wizard} setWizard={setWizard} onClose={()=>{setShowCreate(false);setWizard(1)}} onCreate={createEvent}/>} 
   {event&&<EventDrawer event={event} onClose={()=>setEvent(null)} onGallery={()=>setGallery(true)} />}
   {gallery&&<GalleryPreview photos={PHOTOS} favorites={favorites} toggleFav={toggleFav} onClose={()=>setGallery(false)}/>} 
   {toast&&<div className="toast"><FiCheck/> {toast}</div>}
 </div>
}

function Sidebar({page,setPage,open}){return <aside className={`sidebar ${open?'open':''}`}><div className="brand-lockup"><div className="brand-mark">M</div><div><strong>momentia</strong><small>PHOTOGRAPHY OS</small></div></div><div className="workspace-switch"><span className="workspace-avatar">MS</span><div><b>Momentia Studio</b><small>Agency workspace</small></div><FiChevronDown/></div><nav>{NAV.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon/><span>{label}</span>{id==='events'&&<em>4</em>}</button>)}</nav><div className="sidebar-bottom"><div className="storage-mini"><div><span>Storage</span><b>612 GB / 1 TB</b></div><div className="mini-track"><i style={{width:'61%'}}/></div><small>61% used</small></div><button className="upgrade"><FiTrendingUp/><span><b>Upgrade storage</b><small>Need more space?</small></span></button><div className="user-mini"><span className="avatar">MS</span><div><b>Momentia Studio</b><small>Owner</small></div><FiMoreHorizontal/></div></div></aside>}

function Dashboard({events,onCreate,onEvent,onPage,notify}){return <>
 <div className="page-head"><div><span className="eyebrow">AGENCY OVERVIEW</span><h1>Good evening, Momentia.</h1><p>Everything happening across your photography business.</p></div><button className="primary" onClick={onCreate}><FiPlus/> Create event</button></div>
 <section className="kpi-grid"><Kpi icon={<FiClock/>} label="Active events" value="2" sub="1 live · 1 processing"/><Kpi icon={<FiCalendarIcon/>} label="Upcoming" value="2" sub="Next: 12 Sep"/><Kpi icon={<FiImage/>} label="Photos delivered" value="18,420" sub="+2,840 this month"/><Kpi icon={<FiUsers/>} label="Gallery visitors" value="4,862" sub="+18.4% vs last month"/></section>
 <section className="dashboard-main-grid"><div className="section-block"><div className="section-title"><div><span className="eyebrow">LIVE WORK</span><h2>Recent events</h2></div><button className="text-btn" onClick={()=>onPage('events')}>View all <FiChevronRight/></button></div><div className="event-grid">{events.slice(0,3).map(e=><EventCard key={e.id} event={e} onClick={()=>onEvent(e)}/>)}</div></div><aside className="right-column"><StorageWidget/><ActivityWidget notify={notify}/></aside></section>
 <section className="upcoming"><div className="section-title"><div><span className="eyebrow">YOUR CALENDAR</span><h2>Upcoming</h2></div><button className="text-btn" onClick={()=>onPage('events')}>Calendar <FiChevronRight/></button></div><div className="upcoming-list">{events.slice(1,4).map(e=><div className="upcoming-row" key={e.id}><div className="date-box"><b>{e.date.split(' ')[0]}</b><small>{e.date.split(' ')[1]?.slice(0,3)}</small></div><div className="upcoming-info"><b>{e.name}</b><span>{e.venue}</span></div><Status status={e.status}/><span className="upcoming-photos">{e.photos?`${e.photos.toLocaleString()} photos`:'No photos yet'}</span><button className="icon-btn"><FiMoreHorizontal/></button></div>)}</div></section>
 </>}

function Kpi({icon,label,value,sub}){return <div className="kpi-card"><div className="kpi-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function FiCalendarIcon(){return <span className="calendar-icon">▦</span>}
function EventCard({event,onClick}){return <button className="event-card" onClick={onClick}><div className="event-cover"><img src={event.cover} alt=""/><div className="cover-shade"/><div className="event-status"><Status status={event.status}/></div><span className="event-more"><FiMoreHorizontal/></span></div><div className="event-card-body"><div className="event-date">{event.date} <span>·</span> {event.venue}</div><h3>{event.name}</h3><div className="event-metrics"><span><FiImage/>{event.photos.toLocaleString()}</span><span><FiUsers/>{event.visitors}</span><span><FiUploadCloud/>{event.published?`${Math.round(event.published/event.photos*100)}% live`:'—'}</span></div><div className="progress"><i style={{width:`${event.photos?Math.round(event.published/event.photos*100):0}%`}}/></div></div></button>}
function Status({status}){const cls=status.toLowerCase();return <span className={`status ${cls}`}><i/>{status}</span>}
function StorageWidget(){return <div className="widget"><div className="widget-head"><div><span className="eyebrow">MEDIA STORAGE</span><h3>Your storage</h3></div><FiHardDrive/></div><div className="storage-number"><strong>612 GB</strong><span>of 1 TB</span></div><div className="storage-track"><i style={{width:'61%'}}/></div><div className="storage-breakdown"><span><i className="dot photos"/>Photos <b>584 GB</b></span><span><i className="dot files"/>Other <b>28 GB</b></span></div><button className="secondary full">Manage storage</button></div>}
function ActivityWidget({notify}){return <div className="widget"><div className="widget-head"><div><span className="eyebrow">RECENT ACTIVITY</span><h3>What's happening</h3></div><button className="icon-btn"><FiMoreHorizontal/></button></div><div className="activity"><Activity icon={<FiUploadCloud/>} title="1,842 photos processed" sub="Ananya & Rahul · 8 min ago"/><Activity icon={<FiUsers/>} title="New gallery visitor" sub="Ananya & Rahul · 22 min ago"/><Activity icon={<FiCheck/>} title="Gallery published" sub="Riya & Karan · 1 hr ago"/><Activity icon={<FiCreditCard/>} title="Payment received" sub="₹28,500 · 3 hrs ago"/></div><button className="text-btn full-text" onClick={()=>notify('Activity center coming next')}>View activity <FiChevronRight/></button></div>}
function Activity({icon,title,sub}){return <div className="activity-row"><span>{icon}</span><div><b>{title}</b><small>{sub}</small></div></div>}

function Events({events,onCreate,onEvent}){return <><div className="page-head"><div><span className="eyebrow">EVENT MANAGEMENT</span><h1>Events</h1><p>Create, publish and deliver every event from one place.</p></div><button className="primary" onClick={onCreate}><FiPlus/> Create event</button></div><div className="filter-bar"><div className="segmented"><button className="active">All <b>{events.length}</b></button><button>Live <b>1</b></button><button>Processing <b>1</b></button><button>Scheduled <b>1</b></button><button>Drafts <b>1</b></button></div><button className="secondary"><FiGrid/> Grid</button></div><div className="events-page-grid">{events.map(e=><EventCard key={e.id} event={e} onClick={()=>onEvent(e)}/>)}</div>{!events.length&&<Empty icon={<FiSearch/>} title="No events found" text="Try a different search."/>}</>}

function PhotoLibrary({favorites,toggleFav,onGallery}){const [filter,setFilter]=useState('All');const [query,setQuery]=useState('');const cats=['All','Wedding','Reception','Portraits','Details','Candid'];const visible=PHOTOS.filter(p=>(filter==='All'||p.tag===filter)&&p.title.toLowerCase().includes(query.toLowerCase()));return <><div className="page-head"><div><span className="eyebrow">MEDIA LIBRARY</span><h1>Photos</h1><p>1,842 photographs · Ananya & Rahul</p></div><div className="head-actions"><button className="secondary"><FiDownload/> Export</button><button className="primary"><FiUploadCloud/> Upload photos</button></div></div><div className="photo-toolbar"><div className="photo-cats">{cats.map(c=><button className={filter===c?'active':''} key={c} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="photo-search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search photos…"/></div><button className="secondary" onClick={onGallery}>Preview gallery</button></div><div className="library-summary"><span>{visible.length} shown</span><span>{favorites.size} favorites</span><span>Auto publishing enabled</span></div><div className="masonry">{visible.map(p=><Photo key={p.id} p={p} favorite={favorites.has(p.id)} toggleFav={toggleFav}/>)}</div></>}
function Photo({p,favorite,toggleFav}){return <button className={`photo ${p.ratio}`}><img src={p.src} alt={p.title}/><span className="photo-overlay"><span>{p.title}</span><button className={`favorite ${favorite?'active':''}`} onClick={e=>{e.stopPropagation();toggleFav(p.id)}}>{favorite?'♥':'♡'}</button></span></button>}

function Team(){return <><div className="page-head"><div><span className="eyebrow">WORKSPACE</span><h1>Team</h1><p>Manage photographers, editors and admins.</p></div><button className="primary"><FiPlus/> Invite member</button></div><div className="team-card"><div className="team-head"><div><h3>4 members</h3><span>All members have access to this agency workspace.</span></div></div>{[['MS','Momentia Studio','Owner','Active'],['AK','Aarav Kumar','Photographer','Active'],['SP','Sneha Patel','Editor','Active'],['RN','Rohan Nair','Photographer','Invited']].map(x=><div className="member-row" key={x[1]}><span className="avatar">{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><Status status={x[3]}/><button className="icon-btn"><FiMoreHorizontal/></button></div>)}</div></>}
function Analytics({events}){return <><div className="page-head"><div><span className="eyebrow">BUSINESS INTELLIGENCE</span><h1>Analytics</h1><p>Understand gallery engagement and delivery performance.</p></div><button className="secondary">Last 30 days <FiChevronDown/></button></div><div className="analytics-kpis"><Kpi label="Gallery views" value="18,420" sub="+21.8%"/><Kpi label="Unique visitors" value="4,862" sub="+18.4%"/><Kpi label="QR scans" value="2,194" sub="+31.2%"/><Kpi label="Downloads" value="1,208" sub="+12.7%"/></div><div className="analytics-grid"><div className="chart-card"><div className="widget-head"><div><span className="eyebrow">ENGAGEMENT</span><h3>Gallery visitors</h3></div><span className="chart-total">4,862</span></div><div className="fake-chart"><i style={{height:'32%'}}/><i style={{height:'45%'}}/><i style={{height:'38%'}}/><i style={{height:'63%'}}/><i style={{height:'52%'}}/><i style={{height:'78%'}}/><i style={{height:'68%'}}/><i style={{height:'91%'}}/><i style={{height:'74%'}}/><i style={{height:'84%'}}/><i style={{height:'100%'}}/><i style={{height:'88%'}}/></div><div className="chart-labels"><span>Aug 1</span><span>Aug 15</span><span>Sep 1</span><span>Sep 8</span></div></div><div className="chart-card"><div className="widget-head"><div><span className="eyebrow">EVENT PERFORMANCE</span><h3>Top galleries</h3></div></div>{events.slice(0,4).map((e,i)=><div className="rank-row" key={e.id}><span>0{i+1}</span><div><b>{e.name}</b><small>{e.visitors} visitors</small></div><strong>{e.photos?Math.round(e.published/e.photos*100):0}%</strong></div>)}</div></div></>}
function Storage(){return <><div className="page-head"><div><span className="eyebrow">MEDIA STORAGE</span><h1>Storage</h1><p>Keep your original files and delivery variants organized.</p></div><button className="primary"><FiPlus/> Upgrade storage</button></div><div className="storage-hero"><div className="storage-ring"><span><b>61%</b><small>used</small></span></div><div><span className="eyebrow">CURRENT PLAN</span><h2>1 TB Agency</h2><p>612 GB used · 388 GB available</p><button className="secondary">Manage plan</button></div></div><div className="storage-table">{[['Original photographs','584 GB','95%'],['Gallery derivatives','18 GB','3%'],['Exports & documents','10 GB','2%']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></>}
function Billing(){return <><div className="page-head"><div><span className="eyebrow">BILLING</span><h1>Plan & billing</h1><p>Manage your subscription, invoices and storage upgrades.</p></div><button className="primary"><FiTrendingUp/> Upgrade plan</button></div><div className="billing-grid"><div className="plan-card"><span className="eyebrow">CURRENT PLAN</span><h2>Studio Pro</h2><strong>₹2,499 <small>/ month</small></strong><p>1 TB storage · unlimited galleries · 5 team members</p><button className="secondary full">Change plan</button></div><div className="invoice-card"><div className="widget-head"><div><span className="eyebrow">INVOICES</span><h3>Recent invoices</h3></div></div>{['Aug 2026','Jul 2026','Jun 2026'].map((m,i)=><div className="invoice-row" key={m}><div><b>Studio Pro</b><small>{m}</small></div><strong>₹2,499</strong><button className="icon-btn"><FiDownload/></button></div>)}</div></div></>}
function Support(){return <><div className="page-head"><div><span className="eyebrow">SUPPORT</span><h1>How can we help?</h1><p>Get help with galleries, uploads, billing and your workspace.</p></div><button className="primary"><FiPlus/> New ticket</button></div><div className="support-grid">{[['Upload & processing','Troubleshoot upload queues and photo processing.','12 articles'],['Gallery delivery','Learn about access, downloads and sharing.','9 articles'],['Billing & storage','Plans, invoices and storage upgrades.','7 articles'],['Team & security','Permissions, invitations and account security.','8 articles']].map(x=><button className="help-card" key={x[0]}><span><FiHelpCircle/></span><div><b>{x[0]}</b><p>{x[1]}</p><small>{x[2]} <FiChevronRight/></small></div></button>)}</div></>}
function Settings(){return <><div className="page-head"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h1>Settings</h1><p>Control your agency profile, security and gallery defaults.</p></div><button className="primary">Save changes</button></div><div className="settings-card">{[['Agency profile','Momentia Studio','Update your public studio information'],['Gallery defaults','Automatic publishing','Choose how new photographs become visible'],['Security','MFA enabled','Protect your workspace and team'],['Notifications','Email + in-app','Choose the updates you receive']].map(x=><div className="setting-row" key={x[0]}><div><b>{x[0]}</b><small>{x[2]}</small></div><button className="setting-value">{x[1]} <FiChevronRight/></button></div>)}</div></>}

function CreateEvent({wizard,setWizard,onClose,onCreate}){const steps=['Event details','Gallery access','Publishing','Downloads','Review'];return <div className="modal-backdrop"><div className="wizard"><div className="wizard-top"><div><span className="eyebrow">NEW EVENT</span><h2>Create event</h2></div><button className="icon-btn" onClick={onClose}><FiX/></button></div><div className="wizard-steps">{steps.map((s,i)=><div className={wizard===i+1?'active':wizard>i+1?'done':''} key={s}><span>{wizard>i+1?<FiCheck/>:i+1}</span><small>{s}</small></div>)}</div><div className="wizard-body">{wizard===1&&<><label>Event name<input placeholder="e.g. Ananya & Rahul"/></label><div className="form-two"><label>Event date<input type="date"/></label><label>Venue<input placeholder="Venue name"/></label></div><label>Client name<input placeholder="Client or couple name"/></label></>}{wizard===2&&<Choice title="Gallery access" options={['Public link','Private link + password','QR code only']} descriptions={['Anyone with the link can view.','Guests need the gallery password.','Designed for on-site event delivery.']}/>} {wizard===3&&<Choice title="Publishing mode" options={['Automatic publishing','Approval before publishing']} descriptions={['Upload → process → gallery automatically.','Your team reviews photographs before publishing.']}/>} {wizard===4&&<Choice title="Download settings" options={['Downloads enabled','Downloads disabled','High-resolution on request']} descriptions={['Guests can download permitted photographs.','Viewing only until you enable downloads.','Guests request originals from your team.']}/>} {wizard===5&&<div className="review"><div><span>EVENT</span><b>Ananya & Rahul</b></div><div><span>ACCESS</span><b>QR code + private link</b></div><div><span>PUBLISHING</span><b>Automatic</b></div><div><span>DOWNLOADS</span><b>High resolution</b></div><div className="review-note"><FiShield/> Guest access is protected and can be revoked anytime.</div></div>}</div><div className="wizard-footer"><button className="secondary" onClick={()=>wizard===1?onClose():setWizard(wizard-1)}>{wizard===1?'Cancel':'Back'}</button>{wizard<5?<button className="primary" onClick={()=>setWizard(wizard+1)}>Continue <FiChevronRight/></button>:<button className="primary" onClick={onCreate}>Create event <FiCheck/></button>}</div></div></div>}
function Choice({title,options,descriptions}){const [selected,setSelected]=useState(0);return <div><h3 className="choice-title">{title}</h3>{options.map((o,i)=><button className={`choice ${selected===i?'selected':''}`} key={o} onClick={()=>setSelected(i)}><span>{selected===i?<FiCheck/>:null}</span><div><b>{o}</b><small>{descriptions[i]}</small></div></button>)}</div>}
function EventDrawer({event,onClose,onGallery}){return <div className="drawer-backdrop"><div className="event-drawer"><div className="drawer-cover"><img src={event.cover} alt=""/><button className="drawer-close" onClick={onClose}><FiX/></button><div><Status status={event.status}/><h2>{event.name}</h2><p>{event.date} · {event.venue}</p></div></div><div className="drawer-body"><div className="drawer-actions"><button className="primary" onClick={onGallery}>Preview gallery</button><button className="secondary">Upload photos</button></div><div className="drawer-stats"><div><b>{event.photos.toLocaleString()}</b><small>Photos</small></div><div><b>{event.published.toLocaleString()}</b><small>Published</small></div><div><b>{event.visitors}</b><small>Visitors</small></div><div><b>{event.scans}</b><small>QR scans</small></div></div><div className="drawer-section"><span className="eyebrow">WORKFLOW</span><h3>Delivery progress</h3><div className="workflow"><span className="done">✓</span><div><b>Photos uploaded</b><small>{event.photos.toLocaleString()} photographs</small></div><i/><span className={event.status==='Live'?'done':''}>{event.status==='Live'?'✓':'2'}</span><div><b>Gallery published</b><small>{event.published.toLocaleString()} visible</small></div><i/><span>3</span><div><b>Delivery</b><small>Guests browse & download</small></div></div></div></div></div></div>}
function GalleryPreview({photos,favorites,toggleFav,onClose}){return <div className="gallery-modal"><header><div className="gallery-brand"><div className="brand-mark">M</div><span>momentia</span></div><div className="gallery-title"><span>LIVE GALLERY</span><h2>Ananya & Rahul</h2></div><div className="gallery-actions"><button className="secondary">Share</button><button className="secondary">Download</button><button className="icon-btn" onClick={onClose}><FiX/></button></div></header><div className="gallery-hero"><div><span className="eyebrow">THE WEDDING OF</span><h1>Ananya <em>&</em> Rahul</h1><p>12 September 2026 · The Leela Palace, Chennai</p><div className="gallery-pills"><span>1,842 photographs</span><span>Live updates</span></div></div></div><div className="gallery-controls"><div><button className="active">All moments</button><button>Ceremony</button><button>Reception</button><button>Portraits</button></div><div><FiSearch/><span>Search</span><button className="secondary">♡ Favorites {favorites.size}</button></div></div><div className="guest-masonry">{photos.map(p=><div className={`guest-photo ${p.ratio}`} key={p.id}><img src={p.src} alt={p.title}/><button className={favorites.has(p.id)?'fav active':'fav'} onClick={()=>toggleFav(p.id)}>{favorites.has(p.id)?'♥':'♡'}</button><span>{p.tag}</span></div>)}</div></div>}
function Empty({icon,title,text}){return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p></div>}
